//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemBRPresentation.App_Start {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemBR_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemBR_Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemBRPresentation.App_Start.SystemBR_Resource", typeof(SystemBR_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail invalido.
        /// </summary>
        internal static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail nao cadastrado.
        /// </summary>
        internal static string M0002 {
            get {
                return ResourceManager.GetString("M0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario esta inativo.
        /// </summary>
        internal static string M0003 {
            get {
                return ResourceManager.GetString("M0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario esta bloqueado.
        /// </summary>
        internal static string M0004 {
            get {
                return ResourceManager.GetString("M0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario ja efetuou um login com a senha provisoria. Favor gerar outra senha.
        /// </summary>
        internal static string M0005 {
            get {
                return ResourceManager.GetString("M0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero de falhas de login superior ao limite diario de falhas.
        /// </summary>
        internal static string M0006 {
            get {
                return ResourceManager.GetString("M0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credenciais invalidas.
        /// </summary>
        internal static string M0007 {
            get {
                return ResourceManager.GetString("M0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha nao pode ser igual a anterior.
        /// </summary>
        internal static string M0008 {
            get {
                return ResourceManager.GetString("M0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha nao foi confirmada corretamente.
        /// </summary>
        internal static string M0009 {
            get {
                return ResourceManager.GetString("M0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro recuperado na consicao de filtro vigente.
        /// </summary>
        internal static string M0010 {
            get {
                return ResourceManager.GetString("M0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Codigo do banco ja existente.
        /// </summary>
        internal static string M0011 {
            get {
                return ResourceManager.GetString("M0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este banco ja contem contas vinculadas. Impossivel ser excluido..
        /// </summary>
        internal static string M0012 {
            get {
                return ResourceManager.GetString("M0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta bancaria ja cadastrada.
        /// </summary>
        internal static string M0013 {
            get {
                return ResourceManager.GetString("M0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel excluir esta conta. Existem lancamentos de CONTAS A PAGAR vinculados a ela.
        /// </summary>
        internal static string M0014 {
            get {
                return ResourceManager.GetString("M0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel excluir esta conta. Existem lancamentos de CONTAS A RECEBER vinculados a ela.
        /// </summary>
        internal static string M0015 {
            get {
                return ResourceManager.GetString("M0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filial ja cadastrada.
        /// </summary>
        internal static string M0016 {
            get {
                return ResourceManager.GetString("M0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel excluir essa filial. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0017 {
            get {
                return ResourceManager.GetString("M0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente ja cadastrado.
        /// </summary>
        internal static string M0018 {
            get {
                return ResourceManager.GetString("M0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel excluir esse cliente. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0019 {
            get {
                return ResourceManager.GetString("M0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor ja cadastrado.
        /// </summary>
        internal static string M0020 {
            get {
                return ResourceManager.GetString("M0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel excluir esse fornecedor. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0021 {
            get {
                return ResourceManager.GetString("M0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto ja cadastrado.
        /// </summary>
        internal static string M0022 {
            get {
                return ResourceManager.GetString("M0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel excluir esse produto. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0023 {
            get {
                return ResourceManager.GetString("M0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Materia prima ja cadastrada.
        /// </summary>
        internal static string M0024 {
            get {
                return ResourceManager.GetString("M0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel excluir essa materia prima. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0025 {
            get {
                return ResourceManager.GetString("M0025", resourceCulture);
            }
        }
    }
}
