//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENDIMENTO_ACOMPANHAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATENDIMENTO_ACOMPANHAMENTO()
        {
            this.ATENDIMENTO_ANEXO = new HashSet<ATENDIMENTO_ANEXO>();
        }
    
        public int ATAC_CD_ID { get; set; }
        public int TIAT_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime ATAC_DT_DATA { get; set; }
        public string ATAC_DS_ACAO { get; set; }
        public int ATAC_IN_ATIVO { get; set; }
    
        public virtual TICKET_ATENDIMENTO TICKET_ATENDIMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATENDIMENTO_ANEXO> ATENDIMENTO_ANEXO { get; set; }
    }
}
