//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLABORADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLABORADOR()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.COLABORADOR_ANEXO = new HashSet<COLABORADOR_ANEXO>();
            this.COLABORADOR_FREQUENCIA = new HashSet<COLABORADOR_FREQUENCIA>();
            this.CONTRATO = new HashSet<CONTRATO>();
            this.DEPENDENTE = new HashSet<DEPENDENTE>();
            this.EXAME_PERIODICO = new HashSet<EXAME_PERIODICO>();
            this.LICENSA_ATESTADO = new HashSet<LICENSA_ATESTADO>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int COLA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> ESCI_CD_ID { get; set; }
        public Nullable<int> ESCO_CD_ID { get; set; }
        public Nullable<int> TISA_CD_ID { get; set; }
        public Nullable<int> VIEM_CD_ID { get; set; }
        public Nullable<int> ESTR_CD_ID { get; set; }
        public Nullable<int> CARG_CD_ID { get; set; }
        public string COLA_NM_NOME { get; set; }
        public string COLA_NM_PAI { get; set; }
        public string COLA_NM_MAE { get; set; }
        public string COLA_NR_CPF { get; set; }
        public string COLA_NR_RG { get; set; }
        public string COLA_NM_RG_EMISSOR { get; set; }
        public Nullable<System.DateTime> COLA_DT_RG { get; set; }
        public string COLA_SG_RG { get; set; }
        public string COLA_NR_ELEITOR { get; set; }
        public Nullable<System.DateTime> COLA_DT_ELEITOR { get; set; }
        public string COLA_NR_ELEITOR_ZONA { get; set; }
        public string COLA_NR_ELEITOR_SECAO { get; set; }
        public string COLA_NM_ELEITOR_MUNICIPIO { get; set; }
        public string COLA_SG_ELEITOR_UF { get; set; }
        public string COLA_NR_NIS { get; set; }
        public string COLA_NR_CTPS { get; set; }
        public string COLA_NR_CTPS_SERIE { get; set; }
        public Nullable<System.DateTime> COLA_DT_CTPS { get; set; }
        public string COLA_SG_CTPS_UF { get; set; }
        public string COLA_NR_RESERVISTA { get; set; }
        public Nullable<System.DateTime> COLA_DT_RESERVISTA { get; set; }
        public string COLA_SG_RESERVISTA_SITUACAO { get; set; }
        public string COLA_NM_RESERVISTA_OM { get; set; }
        public int COLA_IN_SEXO { get; set; }
        public Nullable<System.DateTime> COLA_DT_NASCIMENTO { get; set; }
        public string COLA_NM_CONJUGE { get; set; }
        public string COLA_NM_ENDERECO { get; set; }
        public string COLA_NM_BAIRRO { get; set; }
        public string COLA_NM_CIDADE { get; set; }
        public string COLA_SG_UF { get; set; }
        public string COLA_NR_CEP { get; set; }
        public string COLA_NM_NATURALIDADE { get; set; }
        public string COLA_SG_NATURALIDADE_UF { get; set; }
        public string COLA_NM_NACIONALDADE { get; set; }
        public string COLA_NM_PROFISSAO { get; set; }
        public int COLA_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CARGO CARGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLABORADOR_ANEXO> COLABORADOR_ANEXO { get; set; }
        public virtual ESCALA_TRABALHO ESCALA_TRABALHO { get; set; }
        public virtual ESCOLARIDADE ESCOLARIDADE { get; set; }
        public virtual ESTADO_CIVIL ESTADO_CIVIL { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLABORADOR_FREQUENCIA> COLABORADOR_FREQUENCIA { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
        public virtual TIPO_SALARIAL TIPO_SALARIAL { get; set; }
        public virtual VINCULO_EMPREGATICIO VINCULO_EMPREGATICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPENDENTE> DEPENDENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAME_PERIODICO> EXAME_PERIODICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICENSA_ATESTADO> LICENSA_ATESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
