//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMISSAO_VENDA
    {
        public int COVE_CD_ID { get; set; }
        public int PEVE_CD_ID { get; set; }
        public int VACO_CD_ID { get; set; }
        public decimal COVE_VL_VALOR { get; set; }
    
        public virtual PEDIDO_VENDA PEDIDO_VENDA { get; set; }
        public virtual VALOR_COMISSAO VALOR_COMISSAO { get; set; }
    }
}
