//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_BANCARIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTA_BANCARIA()
        {
            this.CONTA_PAGAR = new HashSet<CONTA_PAGAR>();
            this.CONTA_RECEBER = new HashSet<CONTA_RECEBER>();
        }
    
        public int COBA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int BANC_CD_ID { get; set; }
        public int TICO_CD_ID { get; set; }
        public string COBA_NR_AGENCIA { get; set; }
        public string COBA_NR_CONTA { get; set; }
        public string COBA_NM_AGENCIA { get; set; }
        public string COBA_NM_GERENTE { get; set; }
        public string COBA_NR_TELEFONE { get; set; }
        public Nullable<decimal> COBA_VL_SALDO_INICIAL { get; set; }
        public Nullable<System.DateTime> COBA_DT_ABERTURA { get; set; }
        public int COBA_IN_ATIVO { get; set; }
    
        public virtual BANCO BANCO { get; set; }
        public virtual TIPO_CONTA TIPO_CONTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_PAGAR> CONTA_PAGAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_RECEBER> CONTA_RECEBER { get; set; }
    }
}
