//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_PAGAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTA_PAGAR()
        {
            this.CONTA_PAGAR_ANEXO = new HashSet<CONTA_PAGAR_ANEXO>();
        }
    
        public int CAPA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int PLCO_CD_ID { get; set; }
        public Nullable<int> PECO_CD_ID { get; set; }
        public Nullable<int> COBA_CD_ID { get; set; }
        public Nullable<int> TIFA_CD_ID { get; set; }
        public Nullable<int> FORN_CD_ID { get; set; }
        public System.DateTime CAPA_DT_LANCAMENTO { get; set; }
        public Nullable<decimal> CAPA_VL_VALOR { get; set; }
        public string CAPA_DS_DESCRICAO { get; set; }
        public int CAPA_IN_TIPO_LANCAMENTO { get; set; }
        public string CAPA_NM_FAVORECIDO { get; set; }
        public string CAPA_NM_FORMA_PAGAMENTO { get; set; }
        public int CAPA_IN_LIQUIDADA { get; set; }
        public int CAPA_IN_ATIVO { get; set; }
    
        public virtual CONTA_BANCARIA CONTA_BANCARIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_PAGAR_ANEXO> CONTA_PAGAR_ANEXO { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
        public virtual PEDIDO_COMPRA PEDIDO_COMPRA { get; set; }
        public virtual PLANO_CONTA PLANO_CONTA { get; set; }
        public virtual TIPO_FAVORECIDO TIPO_FAVORECIDO { get; set; }
    }
}
