//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_PARCELAS
    {
        public int CTPA_CD_ID { get; set; }
        public int CONT_CD_ID { get; set; }
        public string CTPA_NR_NUMERO { get; set; }
        public System.DateTime CTPA_DT_VENCIMENTO { get; set; }
        public Nullable<decimal> CTPA_VL_VALOR { get; set; }
        public int CTPA_IN_QUITADA { get; set; }
        public Nullable<decimal> CTPA_VL_RECEBIDO { get; set; }
        public Nullable<System.DateTime> CTPA_DT_RECEBIDO { get; set; }
        public int CTPA_IN_ATIVO { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
    }
}
