//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_RECEBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTA_RECEBER()
        {
            this.CONTA_RECEBER_ANEXO = new HashSet<CONTA_RECEBER_ANEXO>();
        }
    
        public int CARE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public int PLCO_CD_ID { get; set; }
        public Nullable<int> TIFA_CD_ID { get; set; }
        public Nullable<int> PEVE_CD_ID { get; set; }
        public int COBA_CD_ID { get; set; }
        public System.DateTime CARE_DT_LANCAMENTO { get; set; }
        public decimal CARE_VL_VALOR { get; set; }
        public string CARE_DS_DESCRICAO { get; set; }
        public int CARE_IN_TIPO_LANCAMENTO { get; set; }
        public string CARE_NM_FAVORECIDO { get; set; }
        public string CARE_NM_FORMA_PAGAMENTO { get; set; }
        public int CARE_IN_LIQUIDADA { get; set; }
        public int CARE_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CONTA_BANCARIA CONTA_BANCARIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_RECEBER_ANEXO> CONTA_RECEBER_ANEXO { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
        public virtual PEDIDO_VENDA PEDIDO_VENDA { get; set; }
        public virtual PLANO_CONTA PLANO_CONTA { get; set; }
        public virtual TIPO_FAVORECIDO TIPO_FAVORECIDO { get; set; }
    }
}
