//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_SOLICITACAO_APROVACAO
    {
        public int CTSA_CD_ID { get; set; }
        public int CONT_CD_ID { get; set; }
        public System.DateTime CTSA_DT_DATA { get; set; }
        public int COLA_CD_ID { get; set; }
        public string CTSA_DS_RESPOSTA { get; set; }
        public Nullable<int> CTSA_IN_STATUS { get; set; }
        public int CTSA_IN_ATIVO { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
    }
}
