//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPAMENTO
    {
        public int EQUI_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public Nullable<int> CAEQ_CD_ID { get; set; }
        public string EQUI_NR_NUMERO { get; set; }
        public string EQUI_NM_NOME { get; set; }
        public string EQUI_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> EQUI_DT_COMPRA { get; set; }
        public Nullable<decimal> EQUI_VL_VALOR { get; set; }
        public Nullable<int> EQUI_NR_VIDA_UTIL { get; set; }
        public Nullable<System.DateTime> EQUI_DT_BAIXA { get; set; }
        public string EQUI_DS_MOTIVO_BAIXA { get; set; }
        public int EQUI_IN_ATIVO { get; set; }
    
        public virtual CATEGORIA_EQUIPAMENTO CATEGORIA_EQUIPAMENTO { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
    }
}
