//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAME_PERIODICO
    {
        public int EXPE_CD_ID { get; set; }
        public int COLA_CD_ID { get; set; }
        public System.DateTime EXPE_DT_DATA { get; set; }
        public int EXPE_IN_TIPO { get; set; }
        public string EXPE_DS_DESCRICAO { get; set; }
        public int EXPE_IN_ATIVO { get; set; }
    
        public virtual COLABORADOR COLABORADOR { get; set; }
    }
}
