//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONALIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCIONALIDADE()
        {
            this.PLANO_PERMISSAO = new HashSet<PLANO_PERMISSAO>();
        }
    
        public int FUNC_CD_ID { get; set; }
        public string FUNC_SG_SIGLA { get; set; }
        public string FUNC_NM_NOME { get; set; }
        public int FUNC_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANO_PERMISSAO> PLANO_PERMISSAO { get; set; }
    }
}
