//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_ITEM
    {
        public int INIT_CD_ID { get; set; }
        public int INVE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> PROD_CD_ID { get; set; }
        public Nullable<int> MAPR_CD_ID { get; set; }
        public System.DateTime INIT_DT_CONTAGEM { get; set; }
        public int INIT_NR_QUANTIDADE { get; set; }
        public Nullable<int> INIT_IN_ATIVO { get; set; }
    
        public virtual INVENTARIO INVENTARIO { get; set; }
        public virtual MATERIA_PRIMA MATERIA_PRIMA { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
