//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTARIO()
        {
            this.INVENTARIO_ITEM = new HashSet<INVENTARIO_ITEM>();
        }
    
        public int INVE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<int> CAPR_CD_ID { get; set; }
        public Nullable<int> CAMA_CD_ID { get; set; }
        public System.DateTime INVE_DT_DATA { get; set; }
        public string INVE_NM_MOTIVO { get; set; }
        public Nullable<System.DateTime> INVE_DT_CONCLUSAO { get; set; }
        public int INVE_IN_STATUS { get; set; }
        public int INVE_NR_ITENS_CONTADOS { get; set; }
        public int INVE_NR_ITENS_ERRO { get; set; }
        public int INVE_IN_ATIVO { get; set; }
    
        public virtual CATEGORIA_MATERIA CATEGORIA_MATERIA { get; set; }
        public virtual CATEGORIA_PRODUTO CATEGORIA_PRODUTO { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTARIO_ITEM> INVENTARIO_ITEM { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
    }
}
