//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_PROPOSTA_VENDA
    {
        public int ITPV_CD_ID { get; set; }
        public int PRVE_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public int ITPV_QN_QUANTIDADE { get; set; }
        public string ITPV_TX_OBSERVACOES { get; set; }
        public int ITPV_IN_ATIVO { get; set; }
    
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual PROPOSTA_VENDA PROPOSTA_VENDA { get; set; }
    }
}
