//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_AGENDA
    {
        public int ITAG_CD_ID { get; set; }
        public int AGEN_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public string ITAG_NM_NOME { get; set; }
        public string ITAG_DS_DESCRICAO { get; set; }
        public string ITAG_NM_LOCAL { get; set; }
        public System.DateTime ITAG_DT_INICIO { get; set; }
        public System.DateTime ITAG_DT_FINAL { get; set; }
        public string ITAG_NM_PESSOAS { get; set; }
        public int ITAG_IN_ATIVO { get; set; }
    
        public virtual AGENDA AGENDA { get; set; }
    }
}
