//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_PROPOSTA_SERVICO
    {
        public int ITPS_CD_ID { get; set; }
        public int PRSE_CD_ID { get; set; }
        public int SERV_CD_ID { get; set; }
        public int ITPS_QN_QUANTIDADE { get; set; }
        public string ITPS_TX_OBSERVACOES { get; set; }
        public int ITPS_IN_ATIVO { get; set; }
    
        public virtual PROPOSTA_SERVICO PROPOSTA_SERVICO { get; set; }
        public virtual SERVICO SERVICO { get; set; }
    }
}
