//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_PEDIDO_SERVICO
    {
        public int ITPS_CD_ID { get; set; }
        public int PESE_CD_ID { get; set; }
        public int SERV_CD_ID { get; set; }
        public int ITPS_QN_QUANTIDADE { get; set; }
        public decimal ITPS_VL_VALOR { get; set; }
        public string ITPS_TX_OBSERVACOES { get; set; }
        public int ITPS_IN_ATIVO { get; set; }
    
        public virtual PEDIDO_SERVICO PEDIDO_SERVICO { get; set; }
        public virtual SERVICO SERVICO { get; set; }
    }
}
