//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_PEDIDO_COMPRA_COTACAO
    {
        public int ITCC_CD_ID { get; set; }
        public int ITPC_CD_ID { get; set; }
        public Nullable<int> FORN_CD_ID { get; set; }
        public Nullable<int> ITCC_QN_QUANTIDADE { get; set; }
        public Nullable<decimal> ITCC_VL_PRECO_SELECIONADO { get; set; }
        public Nullable<int> ITCC_NR_QUANTIDADE_REVISADA { get; set; }
        public Nullable<System.DateTime> ITCC_DT_VALIDADE { get; set; }
        public string ITCC_NM_FORMA_PAGAMENTO { get; set; }
        public string ITCC_TX_OBSERVACOES { get; set; }
        public int ITCC_IN_ATIVO { get; set; }
    
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual ITEM_PEDIDO_COMPRA ITEM_PEDIDO_COMPRA { get; set; }
    }
}
