//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIA_PRIMA_ANEXO
    {
        public int MAPA_CD_ID { get; set; }
        public int MAPR_D_ID { get; set; }
        public string MAPA_NM_TITULO { get; set; }
        public System.DateTime MAPA_DT_ANEXO { get; set; }
        public int MAPA_IN_TIPO { get; set; }
        public string MAPA_AQ_ARQUIVO { get; set; }
        public int MAPA_IN_ATIVO { get; set; }
    
        public virtual MATERIA_PRIMA MATERIA_PRIMA { get; set; }
    }
}
