//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIA_PRIMA_FORNECEDOR
    {
        public int MAFO_CD_ID { get; set; }
        public Nullable<int> MAPR_CD_ID { get; set; }
        public Nullable<int> FORN_CD_ID { get; set; }
        public int MAFO_IN_ATIVO { get; set; }
    
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual MATERIA_PRIMA MATERIA_PRIMA { get; set; }
    }
}
