//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICACAO
    {
        public int NOTI_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<int> CANO_CD_ID { get; set; }
        public Nullable<System.DateTime> NOTI_DT_DATA { get; set; }
        public int NOTI_IN_ATIVO { get; set; }
        public Nullable<int> NOTI_IN_ENVIADA { get; set; }
        public Nullable<int> NOTI_IN_STATUS { get; set; }
        public string NOTI_IN_TEXTO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CATEGORIA_NOTIFICACAO CATEGORIA_NOTIFICACAO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
