//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPORTUNIDADE_NEGOCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPORTUNIDADE_NEGOCIO()
        {
            this.OPORTUNIDADE_NEGOCIO_ANEXO = new HashSet<OPORTUNIDADE_NEGOCIO_ANEXO>();
        }
    
        public int OPNE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public Nullable<int> PRVE_CD_ID { get; set; }
        public Nullable<int> PRSE_CD_ID { get; set; }
        public string OPNE_NM_NOME { get; set; }
        public System.DateTime OPNE_DT_DATA { get; set; }
        public int OPNE_IN_TIPO_OPORTUNIDADE { get; set; }
        public string OPNE_DS_DESCRICAO { get; set; }
        public string OPNE_DS_ORIGEM { get; set; }
        public int OPNE_IN_STATUS { get; set; }
        public Nullable<System.DateTime> OPNE_DT_MUDANCA_STATUS { get; set; }
        public Nullable<System.DateTime> OPNE_DT_APROVACAO { get; set; }
        public Nullable<System.DateTime> OPNE_DT_CANCELAMENTO { get; set; }
        public string OPNE_DS_JUSTIFICATIVA { get; set; }
        public int OPNE_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPORTUNIDADE_NEGOCIO_ANEXO> OPORTUNIDADE_NEGOCIO_ANEXO { get; set; }
        public virtual PROPOSTA_SERVICO PROPOSTA_SERVICO { get; set; }
        public virtual PROPOSTA_VENDA PROPOSTA_VENDA { get; set; }
    }
}
