//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_VENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO_VENDA()
        {
            this.COMISSAO_VENDA = new HashSet<COMISSAO_VENDA>();
            this.CONTA_RECEBER = new HashSet<CONTA_RECEBER>();
            this.ITEM_PEDIDO_VENDA = new HashSet<ITEM_PEDIDO_VENDA>();
            this.PEDIDO_VENDA_ANEXO = new HashSet<PEDIDO_VENDA_ANEXO>();
            this.PROPOSTA_VENDA = new HashSet<PROPOSTA_VENDA>();
        }
    
        public int PEVE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public string PEVE_NM_NOME { get; set; }
        public System.DateTime PEVE_DT_DATA { get; set; }
        public int PEVE_IN_STATUS { get; set; }
        public Nullable<System.DateTime> PEVE_DT_MUDANCA_STATUS { get; set; }
        public Nullable<System.DateTime> PEVE_DT_APROVACAO { get; set; }
        public Nullable<System.DateTime> PEVE_DT_CANCELAMENTO { get; set; }
        public string PEVE_DS_DESCRICAO { get; set; }
        public string PEVE_DS_JUSTIFICATIVA { get; set; }
        public Nullable<System.DateTime> PEVE_DT_VALIDADE { get; set; }
        public string PEVE_NM_FORMA_PAGAMENTO { get; set; }
        public string PEVE_TX_OBSERVACOES { get; set; }
        public int PEVE_IN_ATIVO { get; set; }
        public string PEVE_NR_NUMERO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMISSAO_VENDA> COMISSAO_VENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_RECEBER> CONTA_RECEBER { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_PEDIDO_VENDA> ITEM_PEDIDO_VENDA { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_VENDA_ANEXO> PEDIDO_VENDA_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPOSTA_VENDA> PROPOSTA_VENDA { get; set; }
    }
}
