//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_SERVICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO_SERVICO()
        {
            this.ITEM_PEDIDO_SERVICO = new HashSet<ITEM_PEDIDO_SERVICO>();
            this.PEDIDO_SERVICO_ANEXO = new HashSet<PEDIDO_SERVICO_ANEXO>();
            this.PROPOSTA_SERVICO = new HashSet<PROPOSTA_SERVICO>();
        }
    
        public int PESE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public string PESE_NM_NOME { get; set; }
        public System.DateTime PESE_DT_DATA { get; set; }
        public int PESE_IN_STATUS { get; set; }
        public Nullable<System.DateTime> PESE_DT_MUDANCA_STATUS { get; set; }
        public Nullable<System.DateTime> PESE_DT_APROVACAO { get; set; }
        public Nullable<System.DateTime> PESE_DT_CANCELAMENTO { get; set; }
        public string PESE_DS_DESCRICAO { get; set; }
        public string PESE_DS_JUSTIFICATIVA { get; set; }
        public System.DateTime PESE_DT_VALIDADE { get; set; }
        public string PESE_NM_FORMA_PAGAMENTO { get; set; }
        public string PESE_TX_OBSERVACOES { get; set; }
        public int PESE_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_PEDIDO_SERVICO> ITEM_PEDIDO_SERVICO { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_SERVICO_ANEXO> PEDIDO_SERVICO_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPOSTA_SERVICO> PROPOSTA_SERVICO { get; set; }
    }
}
