//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANO_ASSINATURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANO_ASSINATURA()
        {
            this.ASSINANTE_PLANO = new HashSet<ASSINANTE_PLANO>();
            this.PLANO_PERMISSAO = new HashSet<PLANO_PERMISSAO>();
        }
    
        public int PLAN_CD_ID { get; set; }
        public string PLAN_NM_NOME { get; set; }
        public System.DateTime PLAN_DT_CADASTRO { get; set; }
        public int PLA_IN_ATIVO { get; set; }
        public System.DateTime PLAN_DT_VALIDADE { get; set; }
        public int PLAN_IN_PROMOCAO { get; set; }
        public decimal PLAN_VL_VALOR { get; set; }
        public Nullable<System.DateTime> PLAN_DT_VALIDADE_PROMOCAO { get; set; }
        public Nullable<decimal> PLAN_VL_VALOR_PROMOCAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSINANTE_PLANO> ASSINANTE_PLANO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANO_PERMISSAO> PLANO_PERMISSAO { get; set; }
    }
}
