//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECO_SERVICO
    {
        public int PRSE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public int SERV_CD_ID { get; set; }
        public decimal PRSE_VL_PRECO_BASE { get; set; }
        public Nullable<decimal> PRSE_VL_PROMOCAO { get; set; }
        public Nullable<System.DateTime> PRSE_DT_VALIDADE { get; set; }
        public int PRSE_IN_ATIVO { get; set; }
    
        public virtual FILIAL FILIAL { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
        public virtual SERVICO SERVICO { get; set; }
    }
}
