//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSTA_VENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPOSTA_VENDA()
        {
            this.ITEM_PROPOSTA_VENDA = new HashSet<ITEM_PROPOSTA_VENDA>();
            this.OPORTUNIDADE_NEGOCIO = new HashSet<OPORTUNIDADE_NEGOCIO>();
            this.PROPOSTA_VENDA_ANEXO = new HashSet<PROPOSTA_VENDA_ANEXO>();
        }
    
        public int PRVE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public Nullable<int> PEVE_CD_ID { get; set; }
        public string PRVE_NM_NOME { get; set; }
        public System.DateTime PRVE_DT_DATA { get; set; }
        public int PRVE_IN_STATUS { get; set; }
        public Nullable<System.DateTime> PRVE_DT_MUDANCA_STATUS { get; set; }
        public Nullable<System.DateTime> PRVE_DT_APROVACAO { get; set; }
        public Nullable<System.DateTime> PRVE_DT_CANCELAMENTO { get; set; }
        public string PRVE_DS_DESCRICAO { get; set; }
        public string PRVE_DS_JUSTIFICATIVA { get; set; }
        public Nullable<System.DateTime> PRVE_DT_VALIDADE { get; set; }
        public string PRVE_NM_FORMA_PAGAMENTO { get; set; }
        public string PRVE_TX_OBSERVACOES { get; set; }
        public int PRVE_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_PROPOSTA_VENDA> ITEM_PROPOSTA_VENDA { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPORTUNIDADE_NEGOCIO> OPORTUNIDADE_NEGOCIO { get; set; }
        public virtual PEDIDO_VENDA PEDIDO_VENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPOSTA_VENDA_ANEXO> PROPOSTA_VENDA_ANEXO { get; set; }
        public virtual ASSINANTE ASSINANTE { get; set; }
    }
}
