//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSTA_SERVICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPOSTA_SERVICO()
        {
            this.ITEM_PROPOSTA_SERVICO = new HashSet<ITEM_PROPOSTA_SERVICO>();
            this.OPORTUNIDADE_NEGOCIO = new HashSet<OPORTUNIDADE_NEGOCIO>();
            this.PROPOSTA_SERVICO_ANEXO = new HashSet<PROPOSTA_SERVICO_ANEXO>();
        }
    
        public int PRSE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public Nullable<int> PESE_CD_ID { get; set; }
        public string PRSE_NM_NOME { get; set; }
        public System.DateTime PRSE_DT_DATA { get; set; }
        public int PRSE_IN_STATUS { get; set; }
        public Nullable<System.DateTime> PRSE_DT_MUDANCA_STATUS { get; set; }
        public Nullable<System.DateTime> PRSE_DT_APROVACAO { get; set; }
        public Nullable<System.DateTime> PRSE_DT_CANCELAMENTO { get; set; }
        public string PRSE_DS_DESCRICAO { get; set; }
        public string PRSE_DS_JUSTIFICATIVA { get; set; }
        public Nullable<System.DateTime> PRSE_DT_VALIDADE { get; set; }
        public string PRSE_NM_FORMA_PAGAMENTO { get; set; }
        public string PRSE_TX_OBSERVACOES { get; set; }
        public int PRSE_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_PROPOSTA_SERVICO> ITEM_PROPOSTA_SERVICO { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPORTUNIDADE_NEGOCIO> OPORTUNIDADE_NEGOCIO { get; set; }
        public virtual PEDIDO_SERVICO PEDIDO_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPOSTA_SERVICO_ANEXO> PROPOSTA_SERVICO_ANEXO { get; set; }
    }
}
