//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSTA_VENDA_ANEXO
    {
        public int PRVA_CD_ID { get; set; }
        public int PRVE_CD_ID { get; set; }
        public string PRVA_NM_TITULO { get; set; }
        public System.DateTime PRVA_DT_ANEXO { get; set; }
        public int PRVA_IN_TIPO { get; set; }
        public string PRVA_AQ_ARQUIVO { get; set; }
        public int PRVA_IN_ATIVO { get; set; }
    
        public virtual PROPOSTA_VENDA PROPOSTA_VENDA { get; set; }
    }
}
