//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSTA_SERVICO_ANEXO
    {
        public int PRSA_CD_ID { get; set; }
        public int PRSE_CD_ID { get; set; }
        public string PRSA_NM_TITULO { get; set; }
        public System.DateTime PRSA_DT_ANEXO { get; set; }
        public int PRSA_IN_TIPO { get; set; }
        public string PRSA_AQ_ARQUIVO { get; set; }
        public int PRSA_IN_ATIVO { get; set; }
    
        public virtual PROPOSTA_SERVICO PROPOSTA_SERVICO { get; set; }
    }
}
