//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_ATENDIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKET_ATENDIMENTO()
        {
            this.ATENDIMENTO_ACOMPANHAMENTO = new HashSet<ATENDIMENTO_ACOMPANHAMENTO>();
        }
    
        public int TIAT_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> MATR_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public Nullable<int> CAAT_CD_ID { get; set; }
        public System.DateTime TIAT_DT_ATENDIMENTO { get; set; }
        public string TIAT_NM_TITULO { get; set; }
        public string TIAT_DS_DESCRICAO { get; set; }
        public int TIAT_IN_STATUS { get; set; }
        public Nullable<System.DateTime> TIAT_DT_FINALIZACAO { get; set; }
        public Nullable<System.DateTime> TIAT_DT_CANCELAMENTO { get; set; }
        public string TIAT_DS_JUSTIFICATIVA { get; set; }
        public int TIAT_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATENDIMENTO_ACOMPANHAMENTO> ATENDIMENTO_ACOMPANHAMENTO { get; set; }
        public virtual CATEGORIA_ATENDIMENTO CATEGORIA_ATENDIMENTO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        public virtual MATRIZ MATRIZ { get; set; }
        public virtual ASSINANTE ASSINANTE { get; set; }
    }
}
